[package]
name = "obs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4" , features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
thiserror = "1"
